// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace FileUploadApi.Entities
{
    public partial class Address
    {
        public int Id { get; set; }
        public string StreetAddress { get; set; }
        public string Suite { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public int StateId { get; set; }
        public DateTime Ts { get; set; }
        public bool Published { get; set; }
    }
}