// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace FileUploadApi.Entities
{
    public partial class GroupAddress
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int AddressId { get; set; }
        public DateTime Ts { get; set; }
        public bool Published { get; set; }
    }
}