// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileUploadApi.Entities
{
    public partial class StateLookup
    {
        public int Id { get; set; }
        public string StateName { get; set; }
        public string Abbreviation { get; set; }
    }
}