// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace FileUploadApi.Entities
{
    public partial class TcwDbContext : DbContext
    {
        public TcwDbContext()
        {
        }

        public TcwDbContext(DbContextOptions<TcwDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<StateLookup> StateLookup { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Record>(entity =>
            {
                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(1000);

                entity.Property(e => e.FilePath).HasMaxLength(255);

                entity.Property(e => e.Ts)
                    .HasColumnType("smalldatetime")
                    .HasColumnName("TS");

            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
